name: sde_dbt_repairshops
version: 1.0.0
config-version: 2

profile: sde_dbt_repairshops

model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [data]
macro-paths: [macros]
target-paths: target
clean-targets: 
  - target
  - dbt_modules
models:
  sde_dbt_repaishops:
    marts:
      core:
        materialized: table
      marketing:
        materialized: view
