config:
  send_anonymous_usage_status: false
sde_dbt_repairshops:
  target: dev
  outputs: 
    dev:
      type: duckdb
      path: ./dbt.duckdb
    prod:
      type: duckdb
      path: ./dbt-prod.duckdb
